version: "3.7"

services:
  php7.3:
    build: .docker/php7.3
    container_name: composer-unused-7.3
    volumes:
      - .:/docker:rw
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=php-dev
      - XDEBUG_CONFIG="idekey=PHPSTORM remote_host=192.168.1.102 remote_port=9001"

  php7.4:
    build: .docker/php7.4
    container_name: composer-unused-7.4
    volumes:
      - .:/docker:rw
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=php-dev
      - XDEBUG_CONFIG="idekey=PHPSTORM remote_host=192.168.1.102 remote_port=9001"